---
title: "Connectivity model summary statistics - raw data"
author: "Liz Stumpner"
date: "2023-06-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.width=15, fig.height=15)
```

```{r}
library(readr)
library(dplyr)
library(stringr)
library(flextable)
library(lubridate)
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(broom)
library(here)
```
The RMD is used to summarize the raw data used in the Connectivity GAM model. The results of the output table are used in the body of the methods text

```{r}

new <- read_csv(here::here("data_publication/data_clean/model_chla_covars.csv"))

#summary stats

dryPd <- new %>%
  filter(inundation == 0) #filtdata 519

wetPd <- new %>%
  filter(inundation == 1) #filtdata 143

#519+143 = 662

data_tbl <- new %>%
  select(chlorophyll, WTmwk, Q_sday, region, water_year, inundation, inund_factor) %>%
  mutate(inund_factor= factor(inund_factor, levels = c("none", "short", "long")))

data_tbl <- unique(data_tbl)

#summarize by inundation factor (none, short, long) and region

data_tbl1a <- data_tbl %>%
  group_by(region, inundation, inund_factor) %>%
  summarize(min_chla = min(chlorophyll),
            max_chla = max(chlorophyll),
            mean_chla = mean(chlorophyll),
            r_chla = max_chla-min_chla,
            sd_chla = sd(chlorophyll),
            min_WTmwk = min(WTmwk),
            max_WTmwk = max(WTmwk),
            mean_WTmwk = mean(WTmwk),
            r_WTmwk = max_WTmwk - min_WTmwk,
            sd_WTmwk = sd(WTmwk),
            min_Q_sday = min(Q_sday),
            max_Q_sday = max(Q_sday),
            mean_Q_sday = mean(Q_sday),
            sd_Q_sday = sd(Q_sday),
            n = n())

#round values
data_tbl1a <- data_tbl1a %>% mutate(across(c(min_chla:sd_WTmwk), \(x) round(x, 1)))
data_tbl1a <- data_tbl1a %>% mutate(across(c(min_Q_sday:sd_Q_sday), \(x) round(x, 0)))
data_tbl1a <- data_tbl1a %>% 
  rename('inun' = 'inundation')

data_tbl1b <- data_tbl %>%
  group_by(inund_factor) %>%
  summarize(chla_5 = quantile(chlorophyll, probs = 0.05),
            chla_95 = quantile(chlorophyll, probs = 0.95),
            chla_mean =mean(chlorophyll),
            wt_5 = quantile(WTmwk, probs = 0.05),
            wt_95 = quantile(WTmwk, probs = 0.95),
            wt_mean = mean(WTmwk),
            Q_5 = quantile(Q_sday, probs = 0.05),
            Q_95 = quantile(Q_sday, probs = 0.95),
            Q_mean = mean(Q_sday),
            n  = n())

data_tbl1b <- data_tbl1b %>% mutate(across(c(chla_5:wt_mean), \(x) round(x, 1)))
data_tbl1b <- data_tbl1b %>% mutate(across(c(Q_5:Q_mean), \(x) round(x, 0)))

data_tbl1c <- data_tbl %>%
group_by(region, inund_factor) %>%
  summarize(chla_5 = quantile(chlorophyll, probs = 0.05),
            chla_95 = quantile(chlorophyll, probs = 0.95),
            chla_mean =mean(chlorophyll),
            wt_5 = quantile(WTmwk, probs = 0.05),
            wt_95 = quantile(WTmwk, probs = 0.95),
            wt_mean = mean(WTmwk),
            Q_5 = quantile(Q_sday, probs = 0.05),
            Q_95 = quantile(Q_sday, probs = 0.95),
            Q_mean = mean(Q_sday),
            n  = n())

data_tbl1c <- data_tbl1c %>% mutate(across(c(chla_5:wt_mean), \(x) round(x, 1)))
data_tbl1c <- data_tbl1c %>% mutate(across(c(Q_5:Q_mean), \(x) round(x, 0)))
#view and save table by inundation factor (none, short, long) and region 

flextable(data_tbl)

write_csv(data_tbl1b, here::here("data_publication/data_clean/raw_data_summary_inunfac.csv"))
write_csv(data_tbl1c, here::here("data_publication/data_clean/raw_data_summary_region_inunfac.csv"))

#summarize by region 

data_tbl2 <- new %>%
  select(chlorophyll, WTmwk, Q_sday, region, water_year)

data_tbl2 <- unique(data_tbl2)

data_tbl2a <- data_tbl2 %>%
  group_by(region) %>%
  summarize(min_chla = min(chlorophyll),
            max_chla = max(chlorophyll),
            mean_chla = mean(chlorophyll),
            r_chla = max_chla-min_chla,
            sd_chla = sd(chlorophyll),
            min_WTmwk = min(WTmwk),
            max_WTmwk = max(WTmwk),
            mean_WTmwk = mean(WTmwk),
            r_WTmwk = max_WTmwk - min_WTmwk,
            sd_WTmwk = sd(WTmwk),
            min_Q_sday = min(Q_sday),
            max_Q_sday = max(Q_sday),
            mean_Q_sday = mean(Q_sday),
            sd_Q_sday = sd(Q_sday),
            n = n())

#round values
data_tbl2a <- data_tbl2a %>% mutate(across(c(min_chla:sd_WTmwk), \(x) round(x, 1)))
data_tbl2a <- data_tbl2a %>% mutate(across(c(min_Q_sday:sd_Q_sday), \(x) round(x, 0)))

data_tbl2b <- data_tbl2 %>%
  group_by(region) %>%
  summarize(chla_5 = quantile(chlorophyll, probs = 0.05),
            chla_95 = quantile(chlorophyll, probs = 0.95),
            chla_mean = mean(chlorophyll),
            wt_5 = quantile(WTmwk, probs = 0.05),
            wt_95 = quantile(WTmwk, probs = 0.95),
            wt_mean = mean(WTmwk),
            Q_5 = quantile(Q_sday, probs = 0.05),
            Q_95 = quantile(Q_sday, probs = 0.95),
            Q_mean = mean(Q_sday),
            n  = n())
  
data_tbl2b <- data_tbl2b %>% mutate(across(c(chla_5:wt_mean), \(x) round(x, 1)))
data_tbl2b <- data_tbl2b %>% mutate(across(c(Q_5:Q_mean), \(x) round(x, 0)))
#view and save table by region 

flextable(data_tbl2)

write_csv(data_tbl2b, here::here("data_publication/data_clean/raw_data_summary_region.csv"))

#summarize by inundation (Y/N) and region
data_tbl3 <- new %>%
  select(chlorophyll, WTmwk, Q_sday, inundation, water_year)

data_tbl3 <- unique(data_tbl3)

data_tbl3 <- data_tbl3 %>%
  group_by(inundation) %>%
  summarize(min_chla = min(chlorophyll),
            max_chla = max(chlorophyll),
            mean_chla = mean(chlorophyll),
            r_chla = max_chla-min_chla,
            sd_chla = sd(chlorophyll),
            min_WTmwk = min(WTmwk),
            max_WTmwk = max(WTmwk),
            mean_WTmwk = mean(WTmwk),
            r_WTmwk = max_WTmwk - min_WTmwk,
            sd_WTmwk = sd(WTmwk),
            min_Q_sday = min(Q_sday),
            max_Q_sday = max(Q_sday),
            mean_Q_sday = mean(Q_sday),
            sd_Q_sday = sd(Q_sday),
            n = n())

#round values
data_tbl3 <- data_tbl3 %>% mutate(across(c(min_chla:sd_WTmwk), \(x) round(x, 1)))
data_tbl3 <- data_tbl3 %>% mutate(across(c(min_Q_sday:sd_Q_sday), \(x) round(x, 0)))

#view and save table by inundation (Y/N) and region

flextable(data_tbl3)

write_csv(data_tbl3, here::here("data_publication/R/raw_data_summary_inun.csv"))


```


```{r}
#summarize by inundation factor and region - most similar to table in the manuscript
data_tbl4<- new %>%
  select(chlorophyll, WTmwk, Q_sday, inund_factor, region, water_year)

data_tbl4 <- unique(data_tbl4)

tbl4_long <- data_tbl4 %>%
  pivot_longer(cols = chlorophyll:Q_sday,
               names_to = "var",
               values_to = "value")

tbl4_summary <- tbl4_long %>%
  group_by(region, inund_factor, var) %>%
  summarize(p5 = round(quantile(value, probs = 0.05),1),
            mean = round(mean(value, na.rm = TRUE),1),
            p95 = round(quantile(value, probs = 0.95),1)) %>%
  arrange(var)

tbl4_wide <- tbl4_summary  %>%
  mutate(inund_factor = factor(inund_factor, levels = c("none", "short", "long"))) %>%
  arrange(inund_factor) %>%
  pivot_wider(names_from = "inund_factor",
              values_from = c(p5, mean, p95)) %>% 
  arrange(var)

data_tbl4 <- data_tbl4 %>%
  group_by(region, inund_factor) %>%
  summarize(chla_5 = quantile(chlorophyll, probs = 0.05),
            chla_95 = quantile(chlorophyll, probs = 0.95),
            chla_mean = mean(chlorophyll),
            wt_5 = quantile(WTmwk, probs = 0.05),
            wt_95 = quantile(WTmwk, probs = 0.95),
            wt_mean = mean(WTmwk),
            Q_5 = quantile(Q_sday, probs = 0.05),
            Q_95 = quantile(Q_sday, probs = 0.95),
            Q_mean = mean(Q_sday),
            n  = n())

write_csv(data_tbl4, here::here("data_publication/data_clean/raw_data_summarytable_inunfac.csv"))
```

