---
title: "Combine_plots"
author: "Catarina Pien"
date: '2022-11-22'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load(here::here("data_model", "upstream_gam_plots.RData"))
load(here::here("data_model", "downstream_gam_plots.RData"))
load(here::here("data_model", "yolo_gam_plots.RData"))
```

```{r}
dd <- downstream_diff + theme(axis.title.y = element_blank())
ud <- upstream_diff + theme(axis.title = element_blank())
yd <- yolo_diff + theme(axis.title = element_blank())


ds <- downstream_same + theme(axis.title.y = element_blank())
us <- upstream_same + theme(axis.title.y = element_blank())
ys <- yolo_same + theme(axis.title = element_blank())
```

```{r}
library(patchwork)
p4 <- ggplot(data.frame(l = dd$labels$y, x = 1, y = 1)) +
      geom_text(aes(x, y, label = l), angle = 90) + 
      theme_void() +
      coord_cartesian(clip = "off")
(plots_diff <- p4 + (ud / yd / dd) + plot_layout(widths = c(1, 25)))
(plots_same <- p4 + (us/ys/ds) + plot_layout(widths = c(1, 25)))
```


```{r}
png(here::here("figures","gam_diffscales.png"), width = 7, height = 8, units = "in", res = 300)
plots_diff
dev.off()


png(here::here("figures","gam_samescales.png"), width = 7, height = 8, units = "in", res = 300)
plots_same
dev.off()
```

