---
title: "VisualizePhyto"
author: "Shruti"
date: "10/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read the phytoplankton data

```{r}
library(ggplot2)
library(tidyverse)
library(lubridate)

phyto.hist = read.csv("../data/EMP_Phytoplankton_1975_2016_Data.csv") %>%
  mutate(date = mdy(SampleDate)) %>% 
#  filter(StationCode %in% c("D22","D24", "C3A"))
  filter(StationCode == "C3A")

ggplot(phyto.hist, aes(x=date, y=Green.Algae)) + geom_point() + facet_wrap(~StationCode, scales = "free") + theme_bw()

```
## Exploring the temperature datasets

# Air temperature CIMIS dataset

```{r}

cimis.lht = read.csv("../data/LHT_CIMIS_daily.csv") %>% 
  mutate(fdate = mdy(Date))

cimis.brt = read.csv("../data/Bryte_CIMIS_daily.csv") %>% 
  mutate(fdate = mdy(Date))

ggplot(cimis.lht, aes(x = fdate, y = Max.Air.Temp..C.)) + geom_point() + theme_bw()

ggplot(cimis.brt, aes(x = fdate, y = Max.Air.Temp..C.)) + geom_point() + theme_bw()



```

