---
title: "Combine_plots"
author: "Catarina Pien"
date: '2022-11-22'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(viridis)
library(ggplot2)
library(dplyr)
library(patchwork)
```

```{r}
load(here::here("data_model", "upstream_gam_plots.RData"))
load(here::here("data_model", "downstream_gam_plots.RData"))
load(here::here("data_model", "yolo_gam_plots.RData"))
```

```{r}
dd <- downstream_diff + theme(axis.title.y = element_blank())
ud <- upstream_diff + theme(axis.title = element_blank())
yd <- yolo_diff + theme(axis.title = element_blank())


ds <- downstream_same + theme(axis.title.y = element_blank())
us <- upstream_same + theme(axis.title.y = element_blank())
ys <- yolo_same + theme(axis.title = element_blank())

dy <- downstream_diffsamey + labs(title = "Downstream") + theme(axis.title.y = element_blank())
uy <- upstream_diffsamey + theme(axis.title = element_blank())
yy <- yolo_diffsamey + labs(title = "Yolo") + theme(axis.title = element_blank())

# working on this ----------------------------------------------------------------------
mylabels = seq(1, 100, 10)
values = c(0,0.5, 1, 1.5, 2)
labels = c()
your_function <- function(x){sprintf("%.1f", 10^as.numeric(x))}
mybreaks = 
dy <- downstream_diffsamey + 
  scale_fill_viridis(breaks = c(0, 0.6931472,1.386294, 1.791759, 2.079442), labels = c(1, 2, 4, 6, 8), option = "turbo",
                     guide = guide_legend(keyheight = 2))+
  labs(title = "Downstream") + 
  theme(axis.title.y = element_blank())
```

```{r}
library(patchwork)
p4 <- ggplot(data.frame(l = dd$labels$y, x = 1, y = 1)) +
      geom_text(aes(x, y, label = l), angle = 90) + 
      theme_void() +
      coord_cartesian(clip = "off")
(plots_diff <- p4 + (ud / yd / dd) + plot_layout(widths = c(1, 25)))
(plots_same <- p4 + (us/ys/ds) + plot_layout(widths = c(1, 25)))
(plots_samey <- p4 + (uy / yy / dy)+ plot_layout(widths = c(1, 25)))
```

# boxplots
```{r}
load("data_model/gams_origdata.Rdata")
data_bp <- alldata %>%
  filter(region!= "cache") %>%
  mutate(region = case_when(region == "above" ~ "Mainstem",
                            region == "below" ~ "Downstream",
                            region == "yolo" ~ "Floodplain"),
         region = factor(region, levels = c("Mainstem", "Floodplain", "Downstream")))
```

```{r}
(chlorophyll <- ggplot(data_bp) + geom_jitter(aes(x = region, y = chlorophyll, color = inund_fac2)) +
  geom_boxplot(aes(x = region, y = chlorophyll), alpha = 0) + 
  scale_color_viridis(discrete = TRUE, option = "turbo") +
  labs(y = "Chlorophyll a (ug/L)", color = "Inundation Duration") +
  theme_bw() +
  theme(axis.title.x = element_blank()))

(chlorophyll_t <- ggplot(data_bp) + geom_jitter(aes(x = region, y = log_chla, color = inund_fac2)) +
  geom_boxplot(aes(x = region, y = log_chla), alpha = 0) + 
  scale_color_viridis(discrete = TRUE, option = "turbo") +
  labs(y = "Log Chlorophyll a (ug/L)", color = "Inundation Duration") +
  theme_bw() +
  theme(axis.title.x = element_blank()))
  
  
flow_t <- ggplot(data_bp) + geom_jitter(aes(x = region, y = log_qsdy, color = inund_fac2)) +
  geom_boxplot(aes(x = region, y = log_qsdy), alpha = 0) + 
  scale_color_viridis(discrete = TRUE, option = "turbo") +
  labs(y = "Log Daily\nMean Flow (cfs)", color = "Inundation Duration") +
  theme_bw() +
  theme(axis.title.x = element_blank())

flow <- ggplot(data_bp) + geom_jitter(aes(x = region, y = Q_sday, color = inund_fac2)) +
  geom_boxplot(aes(x = region, y = Q_sday), alpha = 0) + 
  scale_color_viridis(discrete = TRUE, option = "turbo") +
  labs(y = "Daily Mean Flow (cfs)", color = "Inundation Duration") +
  theme_bw() +
  theme(axis.title.x = element_blank())

(boxplots_flow <- flow_t /flow + plot_layout(guides = "collect") & theme(legend.position = "top"))

(wt_t <- ggplot(data_bp) + geom_jitter(aes(x = region, y = WTmwk, color = inund_fac2)) +
  geom_boxplot(aes(x = region, y = log_qsdy), alpha = 0) + 
  scale_color_viridis(discrete = TRUE, option = "turbo") +
  labs(y = "Mean Weekly\nWater Temperature (°C)", color = "Inundation Duration") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        legend.position = "top"))

(inundation <- ggplot(data_bp %>% group_by(region, inund_fac2) %>%summarize(n = n())) +
    geom_col(aes(x = region, y= n, color = inund_fac2, fill = inund_fac2), alpha = 0.5) +
    scale_color_viridis(discrete = TRUE, option = "turbo") +
    scale_fill_viridis(discrete = TRUE,option = "turbo") +
  labs(y = "Count", color = "Inundation Duration", fill = "Inundation Duration") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        legend.position = "none"))

(boxplots <-  (chlorophyll_t & chlorophyll)/(flow_t &flow) / (wt_t&inundation)+ plot_layout(guides = "collect") & theme(legend.position = "top"))
```

```{r}
ggplot(data_bp) + geom_point(aes(log_chla, chlorophyll))
```

# By inundation duration and region
```{r}
(chlorophyll <- ggplot(data_bp) + geom_jitter(aes(x = region, y = chlorophyll, color = inund_fac2, alpha = 0.4)) +
  geom_boxplot(aes(x = region, y = chlorophyll), alpha = 0, size = 0.6) + 
  scale_color_viridis(discrete = TRUE, option = "turbo") +
   facet_wrap(~inund_fac2) +
  labs(y = "Chlorophyll a (ug/L)", color = "Inundation Duration") +
  theme_bw() +
  theme(axis.title.x = element_blank()))

(chlorophyll_t <- ggplot(data_bp) + geom_jitter(aes(x = region, y = log_chla, color = inund_fac2), alpha = 0.4) +
  geom_boxplot(aes(x = region, y = log_chla), alpha = 0, size = 0.6) + 
       facet_wrap(~inund_fac2) +
  scale_color_viridis(discrete = TRUE, option = "turbo") +
  labs(y = "Log Chlorophyll a (ug/L)", color = "Inundation Duration") +
  theme_bw() +
  theme(axis.title.x = element_blank()))
  
  
flow_t <- ggplot(data_bp) + geom_jitter(aes(x = region, y = log_qsdy, color = inund_fac2), alpha = 0.4) +
  geom_boxplot(aes(x = region, y = log_qsdy), alpha = 0, size = 0.6) + 
     facet_wrap(~inund_fac2) +
  scale_color_viridis(discrete = TRUE, option = "turbo") +
  labs(y = "Log Daily\nMean Flow (cfs)", color = "Inundation Duration") +
  theme_bw() +
  theme(axis.title.x = element_blank())

flow <- ggplot(data_bp) + geom_jitter(aes(x = region, y = Q_sday, color = inund_fac2), alpha = 0.4) +
  geom_boxplot(aes(x = region, y = Q_sday), alpha = 0, size = 0.6) + 
     facet_wrap(~inund_fac2) +
  scale_color_viridis(discrete = TRUE, option = "turbo") +
  labs(y = "Daily Mean Flow (cfs)", color = "Inundation Duration") +
  theme_bw() +
  theme(axis.title.x = element_blank())

(boxplots_flow <- flow_t /flow + plot_layout(guides = "collect") & theme(legend.position = "top"))

(wt_t <- ggplot(data_bp) + geom_jitter(aes(x = region, y = WTmwk, color = inund_fac2), alpha = 0.4) +
  geom_boxplot(aes(x = region, y = WTmwk), alpha = 0, size = 0.6) + 
       facet_wrap(~inund_fac2) +
  scale_color_viridis(discrete = TRUE, option = "turbo") +
  labs(y = "Mean Weekly\nWater Temperature (°C)", color = "Inundation Duration") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        legend.position = "top"))

(inundation <- ggplot(data_bp %>% group_by(region, inund_fac2) %>%summarize(n = n())) +
    geom_col(aes(x = region, y= n, color = inund_fac2, fill = inund_fac2), alpha = 0.4) +
    scale_color_viridis(discrete = TRUE, option = "turbo") +
    scale_fill_viridis(discrete = TRUE,option = "turbo") +
  labs(y = "Count", color = "Inundation Duration", fill = "Inundation Duration") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        legend.position = "none"))


(boxplot2 <- wt_t / flow_t /  chlorophyll_t + plot_layout(guides = "collect")& theme(legend.position = "none"))
```

# By region and inundation duration
```{r}
(chlorophyll <- ggplot(data_bp) + 
   geom_jitter(aes(x = inund_fac2, y = chlorophyll, color = region, alpha = 0.4)) +
  geom_boxplot(aes(x = inund_fac2, y = chlorophyll), alpha = 0, size = 0.6) + 
  scale_color_viridis(discrete = TRUE, option = "turbo") +
   facet_wrap(~region) +
  labs(y = "Chlorophyll a (ug/L)", color = "Region") +
  theme_bw() +
  theme(axis.title.x = element_blank()))

(chlorophyll_t <- ggplot(data_bp) + geom_jitter(aes(x = inund_fac2, y = log_chla, color = region), alpha = 0.4) +
  geom_boxplot(aes(x = inund_fac2, y = log_chla), alpha = 0, size = 0.6) + 
       facet_wrap(~region) +
  scale_color_viridis(discrete = TRUE, option = "turbo") +
  labs(y = "Log Chlorophyll a (ug/L)", color = "Region") +
  theme_bw() +
  theme(axis.title.x = element_blank()))
  
  
flow_t <- ggplot(data_bp) + geom_jitter(aes(x = inund_fac2, y = log_qsdy, color = region), alpha = 0.4) +
  geom_boxplot(aes(x = inund_fac2, y = log_qsdy), alpha = 0, size = 0.6) + 
     facet_wrap(~region) +
  scale_color_viridis(discrete = TRUE, option = "turbo") +
  labs(y = "Log Daily\nMean Flow (cfs)", color = "Region") +
  theme_bw() +
  theme(axis.title.x = element_blank())

flow <- ggplot(data_bp) + geom_jitter(aes(x = inund_fac2, y = Q_sday, color = region), alpha = 0.4) +
  geom_boxplot(aes(x = inund_fac2, y = Q_sday), alpha = 0, size = 0.6) + 
     facet_wrap(~region) +
  scale_color_viridis(discrete = TRUE, option = "turbo") +
  labs(y = "Daily Mean Flow (cfs)", color = "Region") +
  theme_bw() +
  theme(axis.title.x = element_blank())

(boxplots_flow <- flow_t /flow + plot_layout(guides = "collect") & theme(legend.position = "top"))

(wt_t <- ggplot(data_bp) + geom_jitter(aes(x = inund_fac2, y = WTmwk, color = region), alpha = 0.4) +
  geom_boxplot(aes(x = inund_fac2, y = WTmwk), alpha = 0, size = 0.6) + 
       facet_wrap(~region) +
  scale_color_viridis(discrete = TRUE, option = "turbo") +
  labs(y = "Mean Weekly\nWater Temperature (°C)", color = "Region") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        legend.position = "none"))

(boxplot3 <- wt_t / flow_t /  chlorophyll_t + plot_layout(guides = "collect")& theme(legend.position = "none"))
```


```{r}
(histogram_qsdy_t <- ggplot(data_bp, aes(log_qsdy)) + 
   labs(x = "Log Daily Mean Flow (cfs)") +
   geom_histogram(color = "black", binwidth = 0.5) + theme_bw()) 

(histogram_qsdy <- ggplot(data_bp, aes(Q_sday)) + 
    labs(x = "Daily Mean Flow (cfs)") +
   geom_histogram(color = "black", binwidth = 5000) + theme_bw()) 

(histogram_chl_t <- ggplot(data_bp, aes(log_chla)) + 
   geom_histogram(color = "black", binwidth = 0.2) + 
    labs(x = "Log Chlorophyll a (ug/L)") + theme_bw()) 

(histogram_chl <- ggplot(data_bp, aes(chlorophyll)) + 
    labs(x = "Chlorophyll a (ug/L)") + 
   geom_histogram(color = "black", binwidth = 2) + theme_bw())

(histos <- (histogram_qsdy_t/histogram_qsdy) | (histogram_chl_t/histogram_chl))

(boxplot4 <- histos/ wt_t / flow_t /  chlorophyll_t  + plot_layout(guides = "collect")& theme(legend.position = "top"))
```






```{r}
data_bp %>%
  group_by(region) %>%
  summarize(minDate = min(dowy),
            maxDate = max(dowy))
```

Export
```{r}
png(here::here("figures","gam_diffscales.png"), width = 7, height = 8, units = "in", res = 300)
plots_diff
dev.off()

png(here::here("figures","gam_samescales.png"), width = 7, height = 8, units = "in", res = 300)
plots_same
dev.off()

png(here::here("figures","gam_samescalesy.png"), width = 8, height = 8, units = "in", res = 300)
plots_samey
dev.off()

png(here::here("figures","boxplots_flow.png"), width = 8, height = 8, units = "in", res = 300)
boxplots_flow
dev.off()

png(here::here("figures","boxplots_data.png"), width = 8, height = 8, units = "in", res = 300)
boxplots
dev.off()






png(here::here("figures","boxplots_databyInund.png"), width = 8, height = 8, units = "in", res = 300)
boxplot2
dev.off()

png(here::here("figures","boxplots_databyRegion.png"), width = 8, height = 8, units = "in", res = 300)
boxplot3
dev.off()

png(here::here("figures","boxplots_datawithHistos.png"), width = 8, height = 8, units = "in", res = 300)
boxplot4
dev.off()

png(here::here("figures","histos.png"), width = 6, height = 4, units = "in", res = 300)
histos
dev.off()

```

