---
title: "Map_stations"
author: "Catarina Pien"
date: "4/5/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(mapview)
library(sf)
library(ggplot2)
```

```{r}
chla_covars <- read_csv("data_model/model_chla_covars_gam.csv")
```

Make map  
```{r}
stas <- chla_covars %>%
    select(latitude, longitude, station_wq_chl, source) %>%
    distinct() %>%
    mutate(latitude = as.numeric(latitude),
           longitude = as.numeric(longitude))

samplesize <- chla_covars %>%
    group_by(station_wq_chl, latitude, longitude) %>%
    summarize(n = n())

stas_sf <- samplesize %>%
  sf::st_as_sf(coords=c("longitude","latitude"), crs=4326, remove=FALSE)


```

# Look at stations
* Above steamboat
* Between steamboat and RV
* RV/Decker

* no shipping channel (56), no western stations, no USGS-....20(n=1)
```{r}
stas_location <- stas_sf %>%
  left_join(stas) %>%
  filter(!(longitude <= -121.8),
         !(station_wq_chl %in% c("56", "USGS-11455420"))) %>%
  mutate(location = case_when(station_wq_chl %in% c("USGS-11447650", "SHR") ~"main_above",
                              station_wq_chl %in% c("LIS", "STTD", 
                                                     "USGS-11455139") ~ "yolo",
                              station_wq_chl %in% c("USGS-11455143", "USGS-382006121401601", "USGS-382010121402301", "USGS-11455146", "USGS-11455276", "USGS-11455166", "USGS-381424121405601", "USGS-11455315", "USGS-11455385", "USGS-11455350", "44", "USGS-11455167", "Pro", "USGS-11455140") ~"off_channel_below",
                              station_wq_chl %in% c("34", "657", "NZ068", "653", "USGS-11455478", "16", "D22") ~ "main_below"))

mapview::mapview(stas_location, zcol = "location", cex = "n")
```

```{r}
chla_locations <- left_join(chla_covars, stas_location)%>%
  filter(!(longitude <= -121.8),
         station_wq_chl != "56")
```

```{r}
ggplot(chla_locations) +
  geom_point(aes(x = date, y = chlorophyll, color = station_wq_chl)) + facet_wrap(~location, scales = "free", nrow = 5) +
  theme(axis.text.x = element_text(angle = 90))

chla_locations %>%
filter(location == "main_above") %>%
  ggplot() +
  geom_point(aes(x = date, y = chlorophyll, color = station_wq_chl))


chla_locations %>%
filter(location == "main_below") %>%
  ggplot() +
  geom_point(aes(x = date, y = chlorophyll, color = station_wq_chl))

off_below <- chla_locations %>% filter(location == "off_channel_below") 
 plotly::ggplotly(ggplot(off_below) +
  geom_point(aes(x = date, y = chlorophyll, color = station_wq_chl)))
```

Map with "final" stations
```{r}
stas_priority <- chla_locations %>%
  filter(!(longitude <= -121.8),
         !(station_wq_chl %in% c("56", "USGS-11455420"))) %>%
  mutate(priority = case_when(station_wq_chl %in% c("STTD", "SHR", "657", "Pro") ~ 1,
                              station_wq_chl %in% c("LIS", "USGS-11447650", "34", "USGS-11455315")~2,
                              station_wq_chl %in% c("USGS-11455139", "NZ068", "44") ~ 3,
                              station_wq_chl %in% c("653", "USGS-11455350") ~ 4,
                              station_wq_chl=="USGS-11455478" ~ 5,
                              station_wq_chl=="16" ~ 6,
                              station_wq_chl=="D22" ~ 7,
                              TRUE~0))
  
```


```{r}
ggplot(stas_priority) + 
  geom_point(aes(x=longitude, y = latitude, color = location), size = 5) + geom_text(aes(longitude, latitude, label = priority))
```

Liberty Island for off-channel?
```{r}
library(mapview)
library(leaflet)

stas_priority_only <- stas_priority %>%
  group_by(station_wq_chl, latitude, longitude, priority, location) %>%
  summarize(n = n(),
            start = first(date))

pal <- colorFactor(c("steelblue", "magenta", "orange", "green"), domain = c("main_below", "main_above", "yolo", "off_channel_below"))

leaflet(stas_priority_only) %>%
  addTiles() %>%
  addCircleMarkers(~longitude, ~latitude, 
                   radius = ~sqrt(n),
                   color = ~pal(location),
                   stroke = FALSE, fillOpacity = 0.6) %>%
  addLabelOnlyMarkers(~longitude, ~latitude,
                      label =  ~priority, 
                      labelOptions = labelOptions(noHide = T,
                                                  direction = 'center',
                                                  textOnly = T))
```


```{r}
numbers <- chla_locations %>%
  arrange(location) %>%
  group_by(location, station_wq_chl) %>%
  summarize(n = n())

data_slice <- chla_locations %>%
  arrange(date, location, station_wq_chl) %>%
  group_by(date) %>%
  slice(1)
```

