---
title: "notes_bayesian_modeling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(glue)

```

# Bayesian Modeling Overview

The objective of this model is to determine how environmental variables during periods of floodplain connectivity influence chlorophyll-a in the North Delta.  

Better understanding of this issue could inform implementation of the Delta Plan, Delta Adapts climate change scenario planning, ITP and BiOp restoration targets and performance metrics. Increasing floodplain connectivity could export fish food downstream, improve native fish survival and reduce reliance on hatcheries.

Jessica Guo provided code for Model 1, off of which all subsequent model iterations were derived.  The code for iterations of the Bayesian model are located in numbered subfolders (e.g., mod01) within the folder /bayes_models.  Model-specific data are generated via scripts/functions/f_make_bayes_x_dataset.R files, where x corresponds to the model number.  As appropriate, model subfolders contain output figures in /fig_out folders and saved initial (start) parameter values in /inits folders. For JAGS models, the R script is a wrapper that brings in and compiles the model-specific data, generates and/or loads initial values, calls the JAGS model (sam_model.JAGS), and visualizes model outputs. See R_workflow.pptx and references to scripts therein for data sources and initial processing.

## Response Variable

In all model iterations, log(chl) was used as the response variable, and in many models the time series spanned date >= 1998-01-01 and < 2020-10-01, with daily measurements as possible.  

## Covariates of Interest

* Sampling station for chlorophyll measurements (random effect); 7 stations (USBR 16, 34, 44, USGS 657, 11455315, 11455350, 11455385) for first 10 models, For mod11, source is Rio Vista station 657 (lat = 38.15167, lon = -121.6883).  Subsequent regional analyses have yolo (STTD; bypass), Rio Vista 11455420 (below), SHR (upstream), and Pro (Cache).
* Flow (discharge) on the same day as the chlorophyll observation 
* Flow at various lags up to 3 weeks prior to chlorophyll sampling 
* Solar radiation - mean daily (Source: daymet), for the first 10 models this is from Yolo Bypass (lat = 38.307857513, lon = -121.692428589).  For mod11, source is Rio Vista station 657 (lat = 38.15167, lon = -121.6883).  Subsequent regional analyses have yolo (STTD; bypass), Rio Vista 657 (below), SHR (upstream), and Pro (Cache).
  SHR (upstream): 38.53188 -121.5280
  STTD (yolo): 	38.35338 -121.6430
  Pro (cache): 38.28080 -121.6651
  657 (downstream): 38.15167 -121.6883
  
* Nutrients (dissolved inorganic nitrogen; DIN) (Sources: IEP Integrated WQ , 1998-2021: USGS (Cloern); EMP; USBR; USGS CA Water Science Center, 2012-2021; DWR Yolo Bypass Monitoring, Chla: 2009-2021)
* Water temperature - max daily, although also range of daily values for >= Mod11
* Air temperature - max daily 
* Tidal stage 
* Number of days of floodplain inundation 
* Other metrics of water quality

## General model notes

Because there can be issues with identifiability in parameter estimates with hierarchical Bayesian models (see Ogle and Barber 2020), all JAGS models use reparameterization approaches to increase identifiability through post-sweeping of random effects.  For these models, new identifiable parameters are produced by "sweeping in" (adding) the mean value of the random effect of station into the intercept parameter estimate, and "sweeping out" (subtracting) the mean value of the random effect from the random effects.  Then these new identifiable parameters (Bstar and Estar) are analyzed and reported.  The Models 01 through 04 before 12/6/21 use a diffuse folded-t prior that was not truncated for the random-effect standard deviation (Gelman 2006), and suffered from non-convergent MCMC chains and autocorrelation of parameters.  Thus, models before Model 04 on 12/6/21 are considered unreliable.  For JAGS models with antecedent variables, priors for weights of individual lags use a variable drawn from gamma distribution divided by the sum of all deltas to avoid using the dirichlet distribution.  

## Model 01 (JAGS)

### Covariates included:
* Past topped (the number of days of floodplain inundation within the last 30 days, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)
* Flow (Q) of the day of chlorophyll observation
* Antecedent flow (Qant), with lagged flow at a maximum of 1, 4, 7, 14, and 21 days prior to the day of chlorophyll observation
* Antecedent solar radiation (Rant), with 7 daily lags of solar radiation up to 7 days prior to the day of chlorophyll observation
* Antecedent air temperature (Tant), with 7 daily lags of air temperature up to 7 days prior to the day of chlorophyll observation

### Notes:
Lack of convergence in MCMC chains and autocorrelation observed in Bstar, sig.eps, and tau.eps. Thinning to 300 did not remedy the autocorrelation. Slopes of Qant and Tant are negative, with positive slopes for Q, Rant, and past topped (although almost a slope of 0 for past topped).  Weights for Qant are slightly greater for 1d and 21d prior, compared to the other lags, but credible intervals for these posteriors are still wide and overlap among all components; results may not be trustworthy due to issues with convergence.

## Model 02 (JAGS)

### Covariates included:
* Past topped (the number of days of floodplain inundation within the last 30 days, when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)
* Flow (Q) on the day of chlorophyll observation
* Antecedent flow (Qant), with lagged flow at a maximum of 1, 4, 7, 14, and 21 days prior to the day of chlorophyll observation
* Antecedent solar radiation (Rant), with lagged flow at a maximum of 1, 4, 7, 14, and 21 days prior to the day of chlorophyll observation
* Antecedent air temperature (Tant), lagged flow at a maximum of 1, 4, 7, 14, and 21 days prior to the day of chlorophyll observation
* Air temperature (Temp) on the day of chlorophyll observation
* Solar radiation (Rad) on the day of chlorophyll observation

### Notes:
Changed Rant and Tant to have lags that match Qant.  Still poor MCMC chain convergence and autocorrelation.  Credible intervals for slopes of Rad and Temp straddle 0, Rant slope is positive, and other covariate slopes do not change much.  Weight on Qant for 21d prior is now noticeably higher than other flow lags; however may not be trustworthy due to issues with convergence.  

## Model 03 (JAGS)

### Covariates included:
* Inundation days (the number of days of floodplain inundation, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)
* Flow (Q) on the day of chlorophyll observation
* Antecedent flow (Qant), with lagged flow at a maximum of 1, 4, 7, 14, and 21 days prior to the day of chlorophyll observation
* Solar radiation (Rad) on the day of chlorophyll observation

### Notes:
As Model 02 was very complicated, limiting interpretation especially with lack of MCMC chain convergence, Model 03 was pared down. Air temperature was thought to be less important for chlorophyll development than solar radiation, thus was removed for this iteration. Credible intervals for slope of Qant now overlaps 0, inundation days also at 0 with no visible credible intervals; however may not be trustworthy due to continued issues with convergence.  

## Model 04 (JAGS)

### Covariates included:
* Flow (Q) on the day of chlorophyll observation
* Antecedent flow (Qant), with lagged flow at a maximum of 1, 4, 7, 14, and 21 days prior to the day of chlorophyll observation

### Notes:
Began saving text model output summaries (see jm_coda_summary.txt).  Model 04 was pared down even more to only focus on flow covariates.  run_20211124.rda reflects continued issues with convergence and autocorrelation of parameter estimates, see associated output files slope_betas_qant.png, and weights_of_qant.png.  Again, interval for Qant straddles 0.  Note also that initial values for covariate B slopes were set at B = rnorm(3,0,1000) for this and previous models (1st argument adjusted based on number of B slopes). 

run_20211206.rda was generated after discussion with J. Guo, who suggested truncating the result for the folded t-prior for the random effect standard deviation to values above 0 as SD shouldn't be negative, and working with starting values for the sampler based on sig.eps posterior values from chains that seemed more reasonable (i.e., closer to 0 or 1).  Another approach suggested was to use the chain(s) associated with the lowest Dsum value for the initial parameter values, where Dsum is the posterior predictive loss (see Gelfand and Ghosh 1998 as an example). A module for estimating DIC was added to this run, to provide a basis for model selection. Implementing these suggestions resulted in MCMC chain convergence and reduction in parameter autocorrelation.  The slope for Q was closer to 0 and with narrower credible intervals compared to Qant's slope, which was larger but with much wider credible intervals.

mod04_Q and mod04_Qant (below) were run to compare with mod04 posteriors, to investigate if there was added value of including both covariates within the same model.  

## Model 04_Q (JAGS)

### Covariates included:
* Flow (Q) on the day of chlorophyll observation

## Model 04_Qant (JAGS)

### Covariates included:
* Antecedent flow (Qant), with lagged flow at a maximum of 1, 4, 7, 14, and 21 days prior to the day of chlorophyll observation

### Notes comparing 04, 04_Q, and 04_Qant versions 
When given separate models, the posterior estimate for Q (in 04_Q) was the same as for Qant (in 04_Qant).  Comparing the posterior of Q with the sum of posteriors of Q and Qant revealed that there is a lot of shared information provided by these 2 covariates.  

## Model 04_rethinking (rethinking)

### Covariates included:
* Flow (Q) on the day of chlorophyll observation

### Notes
Attempted to convert the simplest version of Model 4 to the rethinking package.  This involved converting listed precisions (required by JAGS) in priors to standard deviations, and converting some JAGS syntax related to reparameterizations for identifiability to R syntax.  Issues with not being able to implement the truncated version of the folded t-distribution for sig.eps resulted in abandoning this model.

## Model 05 (JAGS)

### Covariates included:
* Flow (Q) on the day of chlorophyll observation
* Antecedent flow (Qant), with lagged flow at a maximum of 1, 4, 7, 14, and 21 days prior to the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad)

### Notes
Explicitly specified initial starting values for covariate B slopes to be drawn from a much tighter distribution than in previous model iterations to help with convergence (B = rnorm(4,0,1) compared to B = rnorm(4,0,1000)). With the addition of Srad_mwk, Q slope increases and credible interval widens, and Qant slope moves back near 0 with credible interval overlapping 0.  Srad_mwk slope is positive.  Almost all mean weights on Qant lags are slightly below 0.2. 

## Model 05_Inund (JAGS)

### Covariates included:
* Flow (Q) on the day of chlorophyll observation
* Antecedent flow (Qant), with lagged flow at a maximum of 1, 4, 7, 14, and 21 days prior to the day of chlorophyll observation
* Inundation days (the number of days of floodplain inundation, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)

### Notes
As in mod05, Qant slope credible interval overlaps 0.  Inundation days slope has a small positive slope with a VERY tight credible interval.  

## Model 06 (JAGS)

### Covariates included:
* Flow (Q) on the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad)
* Inundation days (the number of days of floodplain inundation, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)
* Wtemp_RIV_mwk, the 7-day average of the daily max water temperature at Rio Vista

### Notes
Water temperature data at Rio Vista was only available for dates >=1999-02-24, or < 2019-12-31, constraining the analyzable data set for the rest of the model.  Like Model 5, Model 6 also had covariate B slopes drawn from a much tighter distribution (B = rnorm(5,0,1)) than in some previous model iterations to prevent parameters from getting stuck in extreme parameter spaces. Wtemp_RIV_mwk slope overlaps 0 with a wide credible interval, while the slope for inundation days is estimated as a value close to 0 with narrow credible intervals.  The correlations between Q and inundation days posteriors, as well as between solar radiation and water temperature were explored (see /fig_out), suggesting each covariate in the pair may provide some duplicated information within the model.  Additional exploration is provided in subsequent mod06 variants, by removing one covariate for each pair and comparing the resultant posterior density for the remaining covariate in the pair (see below).

## Model 06_Inund (JAGS)

### Covariates included:
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad)
* Inundation days (the number of days of floodplain inundation, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)
* Wtemp_RIV_mwk, the 7-day average of the daily max water temperature at Rio Vista

## Model 06_Srad (JAGS)

### Covariates included:
* Flow (Q) on the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad)
* Inundation days (the number of days of floodplain inundation, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)

### Notes
Q and Srad_mwk continue to have relatively larger magnitude betas with higher credible intervals, compared to inund_days that has a lower magnitude beta posterior with a very narrow credible interval.  Included are plots of the observed vs. predicted chlorophyll (with the red 1:1 line), as well as chlorophyll over time for this particularly model because this was our best performing model based on DIC.  On the pred_vs_obs_20220405.png plot, the colored dots are the mean predictions, and colored error bars are credible intervals around predicted means. For pred_obs_time plot, the colored dots are observed chl values, and colored error bars are again credible intervals around predicted means. An R-squared value for predicted vs. observed chl was 0.22.  

Also plotted are cases where the model was predicting high values of chlorophyll although observed chl values were quite low (highpred_lowobs_time_20220405.png).  Those observations were at USBR 16, USBR 34, and USBR 44.   

## Model 06_Wtemp (JAGS)

### Covariates included:
* Flow (Q) on the day of chlorophyll observation
* Wtemp_RIV_mwk, the 7-day average of the daily max water temperature at Rio Vista
* Inundation days (the number of days of floodplain inundation, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)

## Model 06b (JAGS)

### Covariates included:
* Flow (Q) on the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad)
* Inundation days (the number of days of floodplain inundation, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)
* Wtemp_RIV_mwk, the 7-day average of the daily max water temperature at Rio Vista

### Notes
This model is comparable to Model 6, but restricts the data to observations when there is inundation to determine if correlation between Srad_mwk and Wtemp_RIV_mwk decreases during inundation periods. THIS MODEL NEEDS WORK.  

## Model 07 (rethinking)

### Depending on the model, covariates could have included:
* Flow (Q) on the day of chlorophyll observation
* Antecedent flow (Qant), with lagged flow at a maximum of 1, 4, 7, 14, and 21 days prior to the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad)
* Inundation days (the number of days of floodplain inundation, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)
* Wtemp_RIV_mwk, the 7-day average of the daily max water temperature at Rio Vista

### Notes
Model 07 is a second attempt to convert between JAGS and the rethinking package.  It mimics Model 06's covariates.  Therefore, sam_model.JAGS in the /mod07 folder can be ignored.  ulam function within rethinking is used to accommodate the hierarchical model. There are two models within the 07-run-model.R script, the first attempts to mimic the JAGS models but leaves the estimates of Estar and Bstar out (which can be calculated post model run).  The second does the same thing but tries to reparameterize the model to improve identifiability, based on McElreath's Statistical Rethinking section 13.4.2 Reparameterization.  There is also a version with just Q and Qant.  Some analyses are provided based on rethinking commands.  Note I could not figure out how to code a half (truncated at 0) student-t distribution.  It doesn't appear to be available?

## Model 08 (JAGS)

### Covariates included:
* Flow (Q) on the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad).  This variable was first deseasonalized using the stl function, prior to finding the 7-day average of the mean. 
* Inundation days (the number of days of floodplain inundation, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)
* Wtemp_RIV_mwk, the 7-day average of the daily max water temperature at Rio Vista.  This variable was first deseasonalized using the stl function, prior to finding the 7-day average of the max. 

### Notes
Model 8 uses Srad and Wtemp that have each been deseasonalized with the stl function to isolate the seasonal (periodic) component that is then subtracted from the original time series.  The deseasonalized Srad and Wtemp time series are no longer correlated, nor are their corresponding posterior distributions.  The beta posteriors for the deseasonalized Srad and Wtemp seem to approximately switch magnitudes from previous outputs (e.g., see mod06), but given that we want seasonality represented within the analysis, this model does not make sense.

## Model 09_brms (brms and rethinking)

### Covariates included:
* Flow (Q) on the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad).

### Notes
Since this is basically a continuation of mod07 in an attempt to translate the model code from JAGS to brms or rethinking, I used the same f_make_bayes_mod07_dataset.R function to bring in the data.  An advantage of the brms model vs. rethinking is that unlike rethinking, brms has an available half student-t distribution for the random effect of station.  The version of the brms model that finally ended up working was that with only Q and Srad.  Note, however, that the model structure still produced 21 divergent transitions after warmup.  This result may relate to an issue with identifiability with the hierarchical model, and one of the reasons for Bstar/Estar formulation provided within the JAGS models. I had also attempted to code Qant, but unfortunately could not figure out how to represent the dirichlet prior for the weights of the different Qant temporal lags.  As the dirichlet is the conjugate prior for the categorical distribution, I attempted to follow code that sets Qant to a monotonic variable and describe priors as components of that.  However, it didn't work and doesn't make sense in this scenario.  There is some leftover code from mod07 rethinking to aid in translation to brms. 

## Model 10 (JAGS)

### Covariates included:
* Flow (Q) on the day of chlorophyll observation
* Antecedent flow (Qant), with lagged flow at a maximum of 1, 4, 7, 14, and 21 days prior to the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad).
* Inundation days (the number of days of floodplain inundation, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)

### Notes
Up through mod10 uses the 7-station data set within the downstream region.  Mod10 explores lags between increases in Q (or inund_days) and chl, 63-84 d lags not unusual, but may be due to all Q discharge coming from Verona while chl at downstream sites.  Note that this model is still maintaining separate Q and Qant variables, despite evidence that likely both are not needed.  Tried some wavelets (frequency analyses) to identify potential time scales of variation in but didn't see anything useful. Also contains a comparison of predicted (from the model) vs. observed chlorophyll plot, and predicted chl over time (see related plots in mod06_Srad for analogous plots for the best performing model focused on Q, Srad, and inund_days up until that point).  Note that mod10 does not apply new temporal lags explored in this script. Beta for Q was positive while beta for Qant was negative, but may be that these two covariates are correlated.  

## Model 11 (JAGS) - Station 657 only

### Covariates included:
* Antecedent flow (Qant), with lagged flow at a maximum of 14, 35, and 56 days prior to the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad). 
* Inundation days (the number of days of floodplain inundation, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)
* Wtemp_RIV_mwk, the 7-day average of the daily MEAN water temperature at Rio Vista.  This variable was first deseasonalized using the stl function, prior to finding the 7-day average of the daily mean. 
* Wtemprange_RIV_mwk, the 7-day average of the daily max water temperature minus the 7-day average of the daily min water temperature at Rio Vista.  This variable was not deseasonalized.

### Notes
Mod11 only uses station 657 (Rio Vista) to see if performance improved by using only 1 chlorophyll station for data.  Needed to remove first chlorophyll observation in order to be able to calculate longest Qant temporal lag. It also deseasonalizes water temperature, incorporates water temperature range, and incorporates longer temporal lags in the antecedant flow variable.  Dsum and deviance improve to 102 and 294 respectively (compare to best model up to this point - mod06_Srad - at 392 and 925, respectively, that had Q, Srad, inund_days).  It is unclear from this model whether the gain is from deseasonalizing water temp and adding water temp range or from incorporating longer lags. Now that there is no Q in addition to Qant, Qant has a positive slope albeit a large credible interval.  Perhaps also due to extending the lags.  Credible intervals for Wtemp and Wtemprange overlap, perhaps both are not needed.  Qant lag that extends back 2-5 weeks has a greater effect on chl, while lag that extends back 2 weeks has a lesser effect.  Update:  realized that at least for deviance, shouldn't be comparing this model with the data set restricted to station 657 only to previous models with more data across multiple stations. 

## Model 11b (JAGS) - Station 657 only

### Covariates included:
* Antecedent flow (Qant), with lagged flow at a maximum of 1, 7, 21, 42, and 63 days prior to the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad). 
* Inundation days (the number of days of floodplain inundation, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)
* Wtemp_RIV_mwk, the 7-day average of the daily MEAN water temperature at Rio Vista.  This variable was first deseasonalized using the stl function, prior to finding the 7-day average of the daily mean. 
* Wtemprange_RIV_mwk, the 7-day average of the daily max water temperature minus the 7-day average of the daily min water temperature at Rio Vista.  This variable was not deseasonalized.

### Notes
See notes for mod11, except that note that temporal lags for Qant are different for mod11b.  Needed to remove first chlorophyll observation in order to be able to calculate longest Qant temporal lag.  The Dsum and deviance were also basically the same as for mod11, 102 and 295, respectively.  Changing the temporal lags did not really change the beta slope for Qant versus mod11. Weights for Qant show that first week's flows near the bypass don't really affect chl as much as flows that had been near bypass 2-3 weeks prior to chl measurement at Rio Vista.  Flows at longer lags in the past (up to 8 weeks prior) may also affect chl based on higher weights of those Qant terms.  Predictions using both mod11 and mod11b are still not great.  

# Start Regional Models 

## Model 12 (JAGS) - Yolo

### Covariates included:
* Antecedent flow (Qant), with lagged flow at a maximum of 14, 35, and 56 days prior to the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad). 
* Inundation days (the number of days of floodplain inundation, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)
* Wtemp_mwk, the 7-day average of the daily MEAN water temperature at Yolo.  This variable was first deseasonalized using the stl function, prior to finding the 7-day average of the daily mean. 
* Wtemprange_mwk, the 7-day average of the daily max water temperature minus the 7-day average of the daily min water temperature at Yolo.  This variable was not deseasonalized.

### Notes
Trying the next regional model on Yolo only data, but otherwise comparable to Mod11 (however, Yolo data set is quite a bit shorter than below region data set, only 2009-2019).  Like Mod11, Mod12 and all models moving forward are based on the newly compiled data set for regional analysis, where there are region-specific covariates included.  Includes all of the Yolo stations without a random effect of station.  This model was not converging very well for several beta parameters, which provided impetus for exploring other models with the Yolo data, including models with shorter temporal lags for Qant.  

## Model 12_redlags (JAGS) - Yolo

### Covariates included:
* Antecedent flow (Qant), with lagged flow at a maximum of 1, 4, 7, 14, and 21 days prior to the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad). 
* Inundation days (the number of days of floodplain inundation, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)
* Wtemp_mwk, the 7-day average of the daily MEAN water temperature at Yolo.  This variable was first deseasonalized using the stl function, prior to finding the 7-day average of the daily mean. 
* Wtemprange_mwk, the 7-day average of the daily max water temperature minus the 7-day average of the daily min water temperature at Yolo.  This variable was not deseasonalized.

### Notes
Resorted to the temporal lags on Qant from Mod1.  Much better convergence and there was a reduction in Dsum and deviance versus the longer lag model.  Only slight improvement when added Wtemp and Wtemprange to the model with the other 3 covariates than without them.  Days 1 and 4 show greater weights on Qant then do the longer lags.  Qant has a negative slope here, compared to below/Rio Vista models where Qant was positive.

## Model 12_redlags_dowy (JAGS) - Yolo

### Covariates included:
* Antecedent flow (Qant), with lagged flow at a maximum of 1, 4, 7, 14, and 21 days prior to the day of chlorophyll observation
* Day of water year (dowy) - calculated based on a defined Water Year of Oct 1-Sep 30
* Inundation days (the number of days of floodplain inundation, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)

### Notes
Wanted to compare to the GAMS model by investigating whether a general seasonal signal replacement for Srad and Wtemp metrics would provide a better fitting model. Resulted in Dsum = 453.9, Deviance = 846.8 for this model with dowy, versus Dsum = 439, Deviance = 836.2 for Mod 12_redlags with Srad and Wtemp.  Thus, no improvement from replacing Sradm, Wtemp, and Wtemprange with dowy, although should try another model that has both dowy and Wtemprange! 

## Model 12_inund_poss (JAGS) - Yolo

### Covariates included:
* Antecedent flow (Qant), with lagged flow at a maximum of 1, 4, 7, 14, and 21 days prior to the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad). 
* Inundation days (the number of days of floodplain inundation, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)
* Wtemprange_mwk, the 7-day average of the daily max water temperature minus the 7-day average of the daily min water temperature at Yolo.  This variable was not deseasonalized.

### Notes
Following the GAMS model lead, wanted to restrict the data used to the time period when inundation is possible in the system, based on all days of the year when there was at least one inundation event throughout the full all-region dataset.  See scripts/functions/f_make_bayes_mod12inundposs_dataset.R for more information. This is by far the best fitting model so far (check out the pred_vs_obs figure), although based on fewer data points.  Qant continues to be negative for Yolo, and Srad as always is important.  I didn't try with Wtemp in addition to Wtemprange.  Qant lags of 1 and 4 days still have the most weight. Dsum  = 197.7, Deviance = 404.  

## Model 12_inund_poss_flag (JAGS) - Yolo

### Covariates included:
* Antecedent flow (Qant), with lagged flow at a maximum of 1, 4, 7, 14, and 21 days prior to the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad). 
* Inundation (is the floodplain inundated, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)).  
* Wtemprange_mwk, the 7-day average of the daily max water temperature minus the 7-day average of the daily min water temperature at Yolo.  This variable was not deseasonalized.

### Notes
Made the Inundation (Y/N) a factor that interacted with the other covariates, to replace inundation_days.  Dsum  = 195, Deviance = 402. Better than Mod12_inund_poss. Had to redo both this model and Mod12_inund_poss because at first restricted available data to only when inundation (flag) = Y  

## Model 13_below (JAGS)

### Covariates included:
* Antecedent flow (Qant), with lagged flow at a maximum of 14, 35, and 56 days prior to the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad). 
* Wtemp_mwk, the 7-day average of the daily MEAN water temperature in the Below region.  This variable was first deseasonalized using the stl function, prior to finding the 7-day average of the daily mean. 
* Wtemprange_mwk, the 7-day average of the daily max water temperature minus the 7-day average of the daily min water temperature in the Below region.  This variable was not deseasonalized.
* Days of inundation until now, how many days until today's date in the current water year have been inundated
* Inundation (is the floodplain inundated, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs))

### Notes
This model is for the Below region using the new dataset developed after Mod10.  Mod13_below is similar to Mod11 but now expands to other stations beyond just Station 657 below the bypass.  Still no random effect of station.  Replaces inundation_days with days of inundation until now (which should be the same as inundation_days if there is only 1 inundation event, otherwise all days of inundation for all events during the water year are included).  This model codes inundation_season incorrectly as though it is a continuous covariate. Interpretation of Qant lags is not as clear as in Mod11.  Would generally ignore this model.  However, shows wtemprange is not very important in the Below region!

## Model 13_below_inundposs (JAGS)

### Covariates included:
* Antecedent flow (Qant), with lagged flow at a maximum of 14, 35, and 56 days prior to the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad). 
* Wtemp_mwk, the 7-day average of the daily MEAN water temperature in the Below region.  This variable was first deseasonalized using the stl function, prior to finding the 7-day average of the daily mean. 
* Days of inundation until now, how many days until today's date in the current water year have been inundated
* Inundation (is the floodplain inundated, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs))

### Notes
Like Mod12_inund_poss models, this model restricted the dataset to only the season when inundation is possible based on data from all regions.  This time, correctly made the inundation (Y/N) a factor. Model seems to be less well-fit than when isolated data to a single station (Station 657) for the Below region.  Qant peaks 5-8 weeks. Srad still very important, and Qant still positive.  

## Model 13_yolo_inund_notposs (JAGS)

### Covariates included:
* Antecedent flow (Qant), with lagged flow at a maximum of 14, 35, and 56 days prior to the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad). 
* Wtemprange_mwk, the 7-day average of the daily max water temperature minus the 7-day average of the daily min water temperature in the Yolo region.  This variable was not deseasonalized.
* Days of inundation until now, how many days until today's date in the current water year have been inundated

### Notes
By comparing this model with Mod12_inund_poss, we see that when inundation is possible, Wtemp range is more important than Srad for driving chlorophyll concentrations.  When inundation is not possible, Srad has the higher slope.  Qant not very different among the two seasons.    

## Model 13_above (JAGS)

### Covariates included:
* Antecedent flow (Qant), with lagged flow at a maximum of 1, 4, 7, 14, and 21 days prior to the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad). 
* Wtemp_mwk, the 7-day average of the daily MEAN water temperature in the Above region.  This variable was first deseasonalized using the stl function, prior to finding the 7-day average of the daily mean. 
* Wtemprange_mwk, the 7-day average of the daily max water temperature minus the 7-day average of the daily min water temperature in the Above region.  This variable was not deseasonalized.
* Days of inundation until now, how many days until today's date in the current water year have been inundated
* Inundation season, the season when inundation is possible based on data from all regions.

### Notes
This is the first model investigating the responses of chlorophyll in the region Above the bypass to various covariates.  Obviously, Days of inundation until now are not going to matter in this area that can never experience inundation, which is confirmed in the beta slope overlapping zero.  The credible interval for Wtemp also is basically overlapping zero.  Wtemprange has a small positive effect on chlorophyll concentration but nearly as much as in the Yolo region.  What season it is (the inund_season means winter/spring) matters, as we would expect.  Qant is negative, like the Yolo region. Lag of 7 days for Qant seems a bit more important but still is not too much greater than other temporal lags. Dsum = 146.5, deviance = 432.2 

## Model 13_cache_inundposs (JAGS)

### Covariates included:
* Antecedent flow (Qant), with lagged flow at a maximum of 14, 35, and 56 days prior to the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad). 
* Wtemp_mwk, the 7-day average of the daily MEAN water temperature in the Cache region.  This variable was first deseasonalized using the stl function, prior to finding the 7-day average of the daily mean. 
* Wtemprange_mwk, the 7-day average of the daily max water temperature minus the 7-day average of the daily min water temperature in the Cache region.  This variable was not deseasonalized.
* Days of inundation until now, how many days until today's date in the current water year have been inundated
* Inundation season, which is the same as Inundation (is the floodplain inundated, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs))

### Notes
Restricted again to only the season when inundation is possible.  This time focused on the Cache complex region.  Unlike Yolo, Qant slope is positive, but credible interval crosses 0 line.  The scaled data for Cache flow (Q) were basically all negative.  Slopes for posteriors of Srad and Wtemp also positive. Qant temporal lag of 2-5 weeks has the most weight, similar to the downstream region.  Not very many chlorophyll observations, might be difficult for model.  Dsum = 121.1, Deviance = 220.2 

## Model 14_yolo_inund_poss_wtemp (JAGS) 

### Covariates included:
* Antecedent flow (Qant), with lagged flow at a maximum of 1, 4, 7, 14, and 21 days prior to the day of chlorophyll observation
* Srad_mwk, the 7-day average of mean daily solar radiation (i.e., just averaged over a week's worth of Rad). 
* Inundation days (the number of days of floodplain inundation, i.e., when river stage based on Fremont height (>=33.5 ft) and dayflow-QYolo (4,000 cfs)
* Wtemp_mwk, the 7-day average of the daily MEAN water temperature in the Cache region.  This variable was first deseasonalized using the stl function, prior to finding the 7-day average of the daily mean. 
* Wtemprange_mwk, the 7-day average of the daily max water temperature minus the 7-day average of the daily min water temperature at Yolo.  This variable was not deseasonalized.

### Notes
All models with #14 are yolo region.  When adding the flag as a factor in the model (see 14inundposs-wtemprange), measures of fit and deviance:  Dsum = 200, Deviance = 406.4.  no better than when had inund_days instead of flag (compare with Mod12_inund_poss). 

14inundposs-wtemprange-inter: Dsum = 181, Deviance = 388; BETTER!

14inundposs-wtemps: Dsum = 179.3, Deviance = 387.1. Still within 2 for deviance to include both wtemp and wtemprange. about same as previous. Still has interaction with wtemprange + inundation

14inundposs-dowy:  (same as 14inundposs-wtemps but dowy instead of Srad and Wtemp) Dsum = 186.4, Deviance = 392.9. Still has interaction with wtemprange + inundation

14inundposs-lastyr:  Dsum = 180.8, Deviance = 387.8.  Has both wtemp and wtemprange. Still has interaction with wtemprange + inundation.  Not helpful to add days inundated last year.

14inundposs-sincelast:  Dsum = 180.7, Deviance = 387.3. Has both wtemp and wtemprange. Still has interaction with wtemprange + inundation.  Not helpful to add days since last inundated.  

14inundposs-diurnal:  forked from 14inundposs-wtemps.  Not any better to add diurnal range.  Dsum = 179.3, Deviance = 387.

15inundnotposs for below region:  Dsum = 213.6, deviance = 525.3.  Adj R2 = 0.13.

# Stats Links

 - https://statmodeling.stat.columbia.edu/2014/02/12/think-identifiability-bayesian-inference/
 
 - https://bookdown.org/content/4857/models-with-memory.html
 
 - Gelman, A. 2006. https://doi.org/10.1214/06-BA117A
 
- Gelfand, A.E. and S.K. Ghosh, Model choice: A minimum posterior predictive loss approach, Biometrika, Volume 85, Issue 1, March 1998, Pages 1–11, https://doi.org/10.1093/biomet/85.1.1

- Ogle, K. and J.J. Barber (2020). Ensuring identifiability in hierarchical mixed effects Bayesian models. Ecological Applications. https://doi.org/10.1002/eap.2159
