---
title: "nutrient_diagnostics"
output: html_document
date: "2022-09-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#load libraries 
```{r}
library(readr)
library(dplyr)
library(stats)
library(tidyr)
library(ggplot2)
library(ggpubr)
library(lubridate)
library(signal)
library(dataRetrieval)
#remotes::install_github("USGS-R/dataRetrieval")
```

#read in data
```{r}
explore <- read.csv("data_model/model_chla_nuts_combined.csv")

inun <- read.csv("data_model/inundation_with_doy1998.csv")

dat_na <- data.frame(sapply(X = explore, FUN = function(x) sum(is.na(x))))
```
#remove forms of N if not paired with chlorophyll ##break stations up by region 
```{r}

new_dat <- explore[,c(2:5, 7,10,12,14,15)]

new_dat_chl <- new_dat[!is.na(new_dat$chlorophyll),]

sum(is.na(new_dat_chl$diss_nitrate_nitrite == TRUE))

plot(new_dat_chl$latitude, new_dat_chl$diss_nitrate_nitrite)

new_dat_chl$date <- as.POSIXct(new_dat_chl$date, format = "%Y-%m-%d")

unique(new_dat_chl$station_wq_chl)

#add regions to df

regions <- new_dat_chl %>%
  mutate(region = case_when(
        latitude>=38.13&latitude<= 38.22 ~ 'RV',
        latitude>=38.221&latitude<= 38.35 ~ 'CSC',
        latitude>=38.3501&longitude<=-121.568291 ~ 'Yolo',
        longitude>=-121.5727 ~ 'Sac'))

regions <- regions %>% 
  drop_na(region)

ggplot(regions, aes(date, diss_nitrate_nitrite)) + 
  geom_point(color="dark blue") +
  facet_wrap(~region, scales = "fixed")+
  labs(x = 'Date', y = 'NO3 + NO2 (mg/L)') +
  ggtitle('NO3 + NO2')
```
#subset data >= WY 2009  
```{r}
regions_WY09 <- subset(regions, date>="2008-10-01")
```

#add inundation to regions df to explore concentrations during inundated and non-inundated periods

```{r}
regions_WY09$date <- as.Date(regions_WY09$date)

inun$date <- as.Date(inun$date)

inun_nuts <- merge(regions_WY09, inun, by="date", all.x="TRUE")

# identify NO3 + NO2 concentration during bypass inundation 
#red is inun., black is non-inun.

inun_nuts$inundation <- as.character(inun_nuts$inundation)

#NO3+NO2
ggplot(inun_nuts, aes(date, diss_nitrate_nitrite)) + 
  geom_point(color=ifelse(inun_nuts$inundation>0, 'red', 'black')) +
  xlim(c(as.Date('2013-01-01'), as.Date('2020-12-31'))) +
  facet_wrap(~region, scales = "fixed") +
  labs(x = 'Date', y = 'NO3 + NO2 (mg/L)') +
  ggtitle("NO3 + NO2")

#NH4

#ortho-p

#DIN
```
```{r}
#add more diagnostics, include relationship with flow and other covars, include relationship with chl-a and
```

